name = "flashseal"
compatibility_date = "2026-03-11"
pages_build_output_dir = "./public"

[[kv_namespaces]]
binding = "SECRETS"
id = "e70391c8868949458750a2c87b9dec93"
preview_id = "5e2a8d177bf64cc6bc9ab60cc2aa10b0"
